/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const DUCK_ETHEREUM = 'ethereum'

export const ETHEREUM_CREATE_DERIVED_WALLET = 'ETHEREUM/CREATE_DERIVED_WALLET'
export const ETHEREUM_CREATE_WALLET = 'ETHERIUM/CREATE_WALLET'
export const ETHEREUM_SELECT_WALLET = 'ETHEREUM/SELECT_BALANCE'
export const ETHEREUM_UPDATE_BALANCE = 'ETHEREUM/UPDATE_BALANCE'


